<a href="https://colab.research.google.com/github/arorahemant1020/AIML/blob/main/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [20]:
a=np.array([3,7,0,12,56,34,87,12,88,12,9])
a

array([ 3,  7,  0, 12, 56, 34, 87, 12, 88, 12,  9])

In [21]:
b=np.array([1,2,3, 1.684, 5.375, 7.234,6, 77.44, 5, 9, 12])
b

array([ 1.   ,  2.   ,  3.   ,  1.684,  5.375,  7.234,  6.   , 77.44 ,
        5.   ,  9.   , 12.   ])

In [22]:
c=(a+b)
c

array([ 4.   ,  9.   ,  3.   , 13.684, 61.375, 41.234, 93.   , 89.44 ,
       93.   , 21.   , 21.   ])

In [25]:
d= np.array([(1,2,3,4),(5,6,7,8)])
d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
e= np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
e

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [18]:
f=d+e
f

array([[ 2.,  4.,  6.,  8.],
       [10., 12., 14., 16.]])

In [23]:
c.sort()
c

array([ 3.   ,  4.   ,  9.   , 13.684, 21.   , 21.   , 41.234, 61.375,
       89.44 , 93.   , 93.   ])